# Install pre-commit hooks via
# pre-commit install
<<<<<<< HEAD
 
# yapf = yet another python formatter
- repo: git://github.com/pre-commit/mirrors-yapf
  sha: v0.22.0
  hooks:
  - id: yapf
    language: system

# prospector: collection of python linters
- repo: git://github.com/guykisel/prospector-mirror
  sha: b27f281eb9398fc8504415d7fbdabf119ea8c5e1
  hooks:
  - id: prospector
    language: system
    exclude: '^(tests/)|(examples/)'


- repo: local
  hooks:
  - id: version-number
    name: Check version numbers
    entry: python ./.travis-data/check_version.py
=======

# modernizer: make sure our code-base is Python 3 ready
- repo: https://github.com/python-modernize/python-modernize.git
  sha: a234ce4e185cf77a55632888f1811d83b4ad9ef2
  hooks:
  - id: python-modernize
    exclude: ^docs/
    args:
      - --write
      - --nobackups

- repo: local
  hooks:
  # yapf = yet another python formatter
  - id: yapf
    name: yapf
    entry: yapf
    language: system
    types: [python]
    args: ["-i"]

  # prospector: collection of linters
  - id: prospector
    language: system
    types: [file, python]
    name: prospector
    description: "This hook runs Prospector: https://github.com/landscapeio/prospector"
    entry: prospector

  - id: version-number
    name: Check version numbers
    entry: python ./.ci/check_version.py
>>>>>>> cutter/master
    language: system
    files: '^(setup.json)|(aiida_plumed/__init__.py)'
